$(document).ready(function(){
    $('img#richguy').mouseenter(function(){
        $('img#richguy').fadeTo("slow",0);
    });
    $("img#richguy").mouseleave(function(){
        $('img#richguy').fadeTo("slow",1);
    });
    $('button').click(function(){
        $('.vanish').fadeOut("slow");
    });
    $(".animalpic").mouseenter(function(){
        $("#myLionDropDown").toggle("slow");
    });
    $(".animalpic").mouseleave(function(){
        $("#myLionDropDown").toggle("slow");
    });
});
